# Generated by Django 5.2.6 on 2025-10-05 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financekit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='body_ct',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='body_nonce',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='body_tag',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='month',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='year',
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_str',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='receipt',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=512)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financekit.receipt')),
            ],
        ),
    ]
