# Generated by Django 5.2.6 on 2025-10-08 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financekit', '0002_remove_receipt_body_ct_remove_receipt_body_nonce_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='body_ct',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='body_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='body_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
