# Generated by ChatGPT on 2025-11-11
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('financekit', '0004_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
