# Generated by ChatGPT on 2025-11-11
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('financekit', '0005_receipt_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='fees_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tip_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
