# Generated by Django 5.2.6 on 2025-11-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financekit', '0007_receiptitem_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='financekit__created_435cd5_idx',
            old_name='financekit_created_ae_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='financekit__user_id_4c2b3b_idx',
            old_name='financekit_user_created_ae_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='financekit__endpoin_2968ed_idx',
            old_name='financekit_ep_created_ae_idx',
        ),
    ]
